frontend_homepage:
    path:     /
    defaults: { _controller: FrontendBundle:Default:index }
frontend_image:
    path:     /image/{imageName}
    defaults: { _controller: FrontendBundle:Default:image }
frontend_sitemap:
    path:     /sitemap.{_format}
    defaults: { _controller: FrontendBundle:Default:sitemap ,  _format: xml}
    requirements:
      _format:  xml
      
      
frontend_canales:
    path:     /canales.{_format}
    defaults: { _controller: FrontendBundle:Default:canales,  _format: m3u }